config/routes.rb
Rails.application.routes.draw do
  # get 'show_calendar', to: 'drivers#show_calendar'

  get 'tasks' => 'tasks#calendar', as: :tasks
  get 'tasks/new' => 'tasks#new', as: :new_task
  post 'tasks' => 'tasks#create', as: :create_task
  get 'driver/:id/tasks/generate_csv' => 'tasks#generate_csv', as: :generate_csv

  resources :drivers do
    resources :tasks
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :driver

  validates_presence_of :task_type, :start_time, :end_time, :description, :location
  validate :valid_type?,  :no_overlap?, :start_before_end?
  
  VALID_TASK_TYPES = ["pickup", "delivery", "other"]

  def valid_type?
    errors.add(:task_type, "must be a valid type of task") if !VALID_TASK_TYPES.include?(task_type&.downcase)
  end

  def no_overlap?
    overlapping_tasks = Task.where('driver_id = ? AND (? != start_time AND ? != end_time) AND (? BETWEEN start_time AND end_time OR ? BETWEEN start_time AND end_time) ', driver_id, start_time, end_time, start_time, end_time)
    if overlapping_tasks.exists?
      tasks_afterwards = Task.where('driver_id = ? AND ? < end_time', driver_id, start_time).order(:start_time).pluck(:start_time, :end_time)
      tasks_afterwards.each_with_index do |task, i|
        if i == tasks_afterwards.count - 1
          new_start_time = task[1].strftime("%B %d %Y %I:%M%p")
          new_end_time = (task[1] + (end_time - start_time)).strftime("%B %d %Y %I:%M%p")
        elsif (tasks_afterwards[i + 1][0] - task[1]) >= (end_time - start_time)
          new_start_time = task[1].strftime("%B %d %Y %I:%M%p")
          new_end_time = (task[1] + (end_time - start_time)).strftime("%B %d %Y %I:%M%p")
        end

        if new_start_time && new_end_time
          errors.add(:start_time, "or end time overlaps with an existing task. Perhaps #{new_start_time} to #{new_end_time} is better?")
          break
        end
      end
    end
  end

  def start_before_end?
    errors.add(:start_time, "must come after end time") if start_time && end_time && start_time >= end_time
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def index
    @drivers = Driver.all
  end

  def show
  end

  def new
    @driver = Driver.new
  end

  def edit
  end

  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    
  private
    def set_driver
      @driver = Driver.find(params[:id])
    end

    def driver_params
      params.require(:driver).permit(:name)
    end

    def record_not_found
      render :file => "#{Rails.root}/public/404.html", :status => 404
    end
end

app/controllers/tasks_controller.rb
require "csv"

class TasksController < ApplicationController
  before_action :set_driver, except: [:calendar, :new, :create, :generate_csv]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :create_task_type_dropdown
  before_action :create_driver_names_dropdown
  
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  TIME_INTERVALS_IN_DAYS = [2, 4, 7, 14, 28]

  def calendar
    @tasks = Task.all.order(:start_time)
  end

  def index
    @tasks = Task.where(driver: @driver).order(:start_time)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to driver_tasks_url, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to driver_tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_csv
    beginning_of_year = DateTime.current.beginning_of_year
    end_of_year = DateTime.current.end_of_year

    tasks = Task.where(driver_id: params[:id]).pluck(:start_time, :task_type)

    TIME_INTERVALS_IN_DAYS.each do |interval|
      start_day = beginning_of_year
      driver_name = Driver.find(params[:id]).name

      CSV.open("app/reports/#{driver_name}_#{interval}_day_intervals_2020.csv", "w+") do |csv|
        csv << ["Interval"] + Task::VALID_TASK_TYPES
        loop do
          end_day = (start_day + interval.days).end_of_day
          
          data = ["#{start_day.strftime("%B %d")} - #{end_day.strftime("%B %d")}"]
          Task::VALID_TASK_TYPES.each do |type|
            number_of_tasks = tasks.filter{ |task| task[0] >= start_day && task[0] <= end_day && task[1] == type }.count
            data << number_of_tasks
          end
          csv << data

          start_day += interval.days + 1.day
          break if start_day.year > 2020
        end
      end
    end
  end

  private
    def set_driver
      @driver = Driver.find(params[:driver_id])
    end

    def set_task
      @task = Task.where(id: params[:id], driver: @driver).first
      render :file => "#{Rails.root}/public/404.html", :status => 404 if !@task
    end

    def create_task_type_dropdown
      @task_types = Task::VALID_TASK_TYPES.map{ |task| [task, task] }
    end

    def create_driver_names_dropdown
      @driver_names = Driver.pluck(:name, :id)
    end

    def task_params
      params.require(:task).permit(:task_type, :driver_id, :start_time, :end_time, :description, :location)
    end

    def record_not_found
      render :file => "#{Rails.root}/public/404.html", :status => 404
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
        <% driver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show calendar', driver_tasks_path(driver) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if driver %>
  <% model = [driver, task] %>
<% else %>
  <% model = [task] %>
<% end %>

<%= form_with(model: model, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if !driver %>
    <div class="driver">
      <%= form.label :driver_id %>
      <%= form.select :driver_id, options_for_select(driver_names) %>
    </div>
    <br>
  <% end %>

  <div class="field">
    <%= form.label :task_type %>
    <%= form.select :task_type, options_for_select(task_types) %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/calendar.html.erb
<p id="notice"><%= notice %></p>

<h1>All Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Driver Name</th>
      <th>Type</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.driver.name %>
        <td><%= task.task_type %></td>
        <td><%= task.start_time.strftime("%B %d %Y %I:%M%p") %></td>
        <td><%= task.end_time.strftime("%B %d %Y %I:%M%p") %></td>
        <td><%= task.location %></td>
        <td><%= link_to 'Show', driver_task_path(task.driver_id, task) %></td>
        <td><%= link_to 'Edit', edit_driver_task_path(task.driver_id, task) %></td>
        <td><%= link_to 'Destroy', driver_task_path(task.driver_id, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show driver calendar', driver_tasks_path(task.driver_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

<br>
<br>
<br>
<br>

<%= week_calendar number_of_weeks: 2, events: @tasks do |date, tasks| %>
  <%= date %>

  <% tasks.each do |task| %>
    <div>
      <%= link_to "#{task.task_type} (#{task.start_time.strftime("%I:%M%p")} to #{task.end_time.strftime("%I:%M%p")})", driver_task_path(task.driver_id, task) %>
    </div>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task, driver: @driver, driver_names: @driver_names, task_types: @task_types %>

<%= link_to 'Back', driver_tasks_path(@driver) %>

app/views/tasks/index.html.erb
<%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %>

<p id="notice"><%= notice %></p>

<h1>Tasks</h1>
<p><%= @driver.name %></p>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_type %></td>
        <td><%= task.start_time.strftime("%B %d %Y %I:%M%p") %></td>
        <td><%= task.end_time.strftime("%B %d %Y %I:%M%p") %></td>
        <td><%= task.location %></td>
        <td><%= link_to 'Show', driver_task_path(@driver, task) %></td>
        <td><%= link_to 'Edit', edit_driver_task_path(@driver, task) %></td>
        <td><%= link_to 'Destroy', [@driver, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'Main Calendar (all drivers)', tasks_path %>

<br>
<br>

<%= link_to 'New Task', new_task_path %>

<br>
<br>

<%= link_to 'Generate CSV for 2020 tasks', generate_csv_path(@driver.id) %>

<br>
<br>
<br>

<div id="calendar"></div>

<%= week_calendar number_of_weeks: 2, events: @tasks do |date, tasks| %>
  <%= date %>

  <% tasks.each do |task| %>
    <div>
      <%= link_to "#{task.task_type} (#{task.start_time.strftime("%I:%M%p")} to #{task.end_time.strftime("%I:%M%p")})", driver_task_path(@driver, task) %>
    </div>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task, driver_names: @driver_names, driver: @driver, task_types: @task_types %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Driver Name:</strong>
  <%= @task.driver.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @task.task_type %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time.strftime("%B %d %Y %I:%M%p") %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time.strftime("%B %d %Y %I:%M%p") %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @task.location %>
</p>

<%= link_to 'Edit', edit_driver_task_path(@driver, @task) %> |
<%= link_to 'Back', driver_tasks_path(@driver) %>